# Generated by Django 5.1.4 on 2025-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='media/uploaded_excels/'),
        ),
    ]
